server:
  port: 8900

spring:
  profiles:
    active: dev

  web:
    resources:
      cache:
        period: 0
      chain:
        cache: false

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
      additional-paths: src/main/resources/templates,src/main/resources/static

  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html


  application:
    name: fstest-2
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true

